### ISSUE TITLE
NameError: name 'GPT2Tokenizer' is not defined

### ISSUE THREAD

**Issue by rajeevranjan123** [makcedward/nlpaug#115]
I'm flowing these steps:

import nlpaug.augmenter.sentence as nas
aug = nas.ContextualWordEmbsForSentenceAug()

And get this error: 'NameError: name 'GPT2Tokenizer' is not defined'
Please help me to fix these issues.

Thanks in Advance!

**Comment by grayskripko** [comment]
I got similar: `name 'BertTokenizer' is not defined`
If you look at code you'll see something like
```
try:
    import torch
    from transformers import BertTokenizer, BertForMaskedLM
    # from transformers import AutoModel, AutoTokenizer
except ImportError:
    # No installation required if not using this function
    pass
```
So `pip install transformers` should solve this problem.

**Comment by grayskripko** [comment]
@rajeevranjan123 please don't close this issue. I think the project owner should see and react on this thread

**Comment by makcedward** [comment]
You may need to install transformers library first. As not all augmenters use depends on this library, I intend to make it optional. 

`pip install torch>=1.2.0 transformers>=2.5.0`

**Comment by dterg** [comment]
Experiencing this issue with AutoTokenizer, even when transformers is installed. I've identified this to be because of this:

```
try:
    import torch
    from transformers import AutoModelForMaskedLM, AutoTokenizer
except ImportError:
    # No installation required if not using this function
    pass
```

`AutoModelForMaskedLM` is not in transformers 2.9.1 so the import fails, and reverts to the exception which "passes". After upgrading to transformers 3.4.0, this module is available and hence imports correctly. @makcedward
