### ISSUE TITLE
How to use word augmentation for both paragraph and answer in QA task?

### ISSUE THREAD

**Issue by ashawkey** [makcedward/nlpaug#116]
I want to use word augmenter to augment dataset for question-answering task (eg. SQuAD), but I have difficulty augmenting both paragraph and answer.

For example, the synonym augmenter may replace 'many' to 'a plenty of', changing both number of character and word, and if the answer contains this word, simply using start:end slicing leads to wrong result.

Is there a method to transform both paragraph and answer? (like both image and mask in image segmentation task.)

**Comment by makcedward** [comment]
It is designed for augmenting inputs rather than labels. Therefore, updating new position according should be better. To achieve it, you need to know the changing. In other words, you need to know "many" is changing to "a plenty of" and the corresponding position. 

The current design only returns the augmented data but not detail. Will enhance to return those detail as well.

**Comment by ashawkey** [comment]
Thanks for reply! 
I also found it hard to get the details, looking forward to later enhancement.
