### ISSUE TITLE
Can't the model use cuda?

### ISSUE THREAD

**Issue by zhouhuhq** [makcedward/nlpaug#194]
aug = naw.ContextualWordEmbsAug(
    model_path='distilbert-base-uncased', action="substitute", device='cuda:5')
augmented_text = aug.augment(text)

When I used this code, it gave me the following error message：
raceback (most recent call last):
  File "BP_Str_DBLP-Scholar-DA.py", line 62, in <module>
    augmented_text_a = aug.augment(text_a)
  File "/ssd/zhouhcData/.conda/pkgs/deepmatcher/lib/python3.6/site-packages/nlpaug/base_augmenter.py", line 95, in augment
    result = action_fx(clean_data)
  File "/ssd/zhouhcData/.conda/pkgs/deepmatcher/lib/python3.6/site-packages/nlpaug/augmenter/word/context_word_embs.py", line 391, in substitute
    outputs = self.model.predict(masked_texts, target_words=original_tokens, n=2)
  File "/ssd/zhouhcData/.conda/pkgs/deepmatcher/lib/python3.6/site-packages/nlpaug/model/lang_models/distilbert.py", line 97, in predict
    target_token_logits, target_token_idxes = self.filtering(target_token_logits, seed)
  File "/ssd/zhouhcData/.conda/pkgs/deepmatcher/lib/python3.6/site-packages/nlpaug/model/lang_models/language_models.py", line 81, in filtering
    idxes = idxes.detach().numpy().tolist()
TypeError: can't convert cuda:5 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by makcedward** [comment]
Only check the exact match for 'cuda'. [Modified ](https://github.com/makcedward/nlpaug/commit/0a0ef60a7445bf9b424889bab61bf19b0e32c981)to check if "device" include 'cuda'.

Can try dev version (1.1.2dev) first by
`pip install git+https://github.com/makcedward/nlpaug.git`

**Comment by zhouhuhq** [comment]
idxes = idxes.detach().numpy().tolist() --> idxes = idxes.detach().cpu().numpy().tolist() 
Can be used after modification

**Comment by genetixx01** [comment]
Hi makcedward, 
Thanks for this very usefull library. I'm currently trying to use ContextualWordEmbsAug() (with model_path='bert-base-uncased') on google colab in order to run it on GPU but I get the following error. I'm not an expert, but I don't have any problem running Pytorch on GPU. 
Thanks a lot.    

RuntimeError                              Traceback (most recent call last)

<ipython-input-18-477e0aabc79d> in <module>()
      1 #sub_set['aug text'] = sub_set.apply(lambda x: aug.augment(x['text']), axis =1)
      2 # df.apply(lambda x: func(x['col1'],x['col2']),axis=1)
----> 3 aug0 = aug.augment(my_text)
      4 
      5 # aug1 = aug.augment(sub_set.iloc[0,2])

11 frames

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   1911         # remove once script supports set_grad_enabled
   1912         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 1913     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   1914 
   1915 

RuntimeError: Input, output and indices must be on the current device
