### ISSUE TITLE
Optimizations for documents

### ISSUE THREAD

**Issue by petulla** [makcedward/nlpaug#222]
Hi

Are there any optimizations for working with documents?

For example, to use `ContextualWordEmbsAug`, I am randomly sampling sentences and augmenting.

However, this is slow as it requires running inputs through the document parser many times for a given document.

Are there any optimizations to insert more text? For example, using something like longformer to augment an entire document.

**Comment by makcedward** [comment]
For optimizations, I guess you are referring to the speed of generation. Here are some suggestions for that

1. Use GPU. 
2. Pre-generated augmented data instead of generating it during training

For the reason of parsing documents many times due to the training objective of masked language model. By MLM design, masked token should be replaced one by one.
