### ISSUE TITLE
PipelineException: More than one mask_token ([MASK]) is not supported

### ISSUE THREAD

**Issue by sherlcok314159** [makcedward/nlpaug#237]
The code is like:
```python
aug = naw.ContextualWordEmbsAug(model_path="bert-base-uncased", model_type="bert", action="insert")
aug.augment(text,n)
```
And when iterating the dataset, I got the error:

```python
PipelineException: More than one mask_token ([MASK]) is not supported site:stackoverflow.com
```

**Comment by makcedward** [comment]
Ref BERT design, one single mask token can be handled each time. If you do not mind, may you share your value of text?

**Comment by sherlcok314159** [comment]
Code Path is here: https://github.com/sherlcok314159/Files_/blob/main/training.zip. Thanks for replying. :-)

**Comment by makcedward** [comment]
Found the root cause. **[mask]** is a reserved word in BERT (and some transformers-based models). Model will use other context to predict **[mask]** which is handled by nlpaug. It does not expect input data include this reserved word. 

From your data, the original input data include this reserved word. Suggest to do data preprocessing to handle it before passing to nlpaug.
![image](https://user-images.githubusercontent.com/36614806/136139590-0d4d71fb-cad2-4029-bb4f-6d7a3149bfc5.png)
