### ISSUE TITLE
Has ContextualWordEmbsAug gone slow? 

### ISSUE THREAD

**Issue by rajat-tech-002** [makcedward/nlpaug#248]
I had used ContextualWordEmbsAug for larger datasets earlier also. Has the code been significantly affected by some update. The augmentor speed is too slow now.

**Comment by 050644zf** [comment]
I'm using this augmentor recently too and it takes 90 secs to process an sentence on my machine. and still take seconds on colab.

**Comment by rajat-tech-002** [comment]
@050644zf, so you also faced same issue?

**Comment by 050644zf** [comment]
> @050644zf, so you also faced same issue?

Yes, [here](https://colab.research.google.com/drive/1oducHDGMZ5GbCMlmOxucfRpnjByCozMt?usp=sharing) is a testing notebook. You can see still takes 2.5sec to process an sentence.

**Comment by makcedward** [comment]
@rajat-tech-002 
May I know which nlpaug version do you use? Supposed that speed should be improved for ContextualWordEmbsAug after applying tuning to fit multiple inputs to transformer's models.

**Comment by makcedward** [comment]
Tested from version [1.1.5](https://colab.research.google.com/drive/1QTM9YORItSlDVrdXHMQ1X86XW4fpJ80Q?usp=sharing) to [1.1.8](https://colab.research.google.com/drive/1IbXLgbhiQYzHVNxNJu4GtvqU4wPdQhUd?usp=sharing)

Performance is downgraded by 23%.  (13.3s vs 16.4s) for 100 same inputs

**Comment by rajat-tech-002** [comment]
> @rajat-tech-002 May I know which nlpaug version do you use? Supposed that speed should be improved for ContextualWordEmbsAug after applying tuning to fit multiple inputs to transformer's models.

I am using the latest version.

**Comment by rajat-tech-002** [comment]
Please close the issue. 
I think on longer texts for eg. Yahoo dataset with average sentence length of 127, the augmenter would be very slow. 
For eg. 300 seconds for 400 sentences on A100 GPU. 
And it would be more if you do aug_max = None. 
and aug_p = 30%

**Comment by makcedward** [comment]
Longer sentences affect performance as transformers need to handle more text rather than padding. Secondly, more percentage of augmentation affect performance more seriously. 

More technical details: 
For example, 10 tokens will be augmented, It needs to pass through transformers 10 times rather than 1 time. By BERT (or other models) design, masking language modeling predicts one token at a time.

However, I just notice there is major performance downgrade from [1.1.3](https://colab.research.google.com/drive/1Q5fj3DX3HkzuDbrQe6uAkf0he7bB5FWt?usp=sharing) to [1.1.4](https://colab.research.google.com/drive/1A152yd4M5Lzo6rjP-gmFSNnklusT_xC0?usp=sharing). Time spending increased from 1s to 9s. The major change is adopting HuggingFace API rather than using my custom implementation. More tests need to conduct in order to identify the root cause.
