### ISSUE TITLE
Referring to Kobayashi (2018) for BertAug seems not correct and misleading

### ISSUE THREAD

**Issue by shuntaroy** [makcedward/nlpaug#25]
Thank you for your work, I'm using your library for my experiments.

You cite Kobayashi (2018) for the reference of BertAug, but to me, it looks not correct.
Although Kobayashi uses (RNN-based) LM for a similarity-based word replacement, the novelty of his work is **conditional constraint**, which allows keeping the important words for classification (e.g. positivity-indicating words like _fantastic_ for sentiment analysis).
You might want to read Sec 2.3 of the work.

As far as my understanding, your code does not implement the conditional constraint objective.
If you would keep citing the reference, the objective should be implemented.
Otherwise, I guess it's misleading.

**Comment by makcedward** [comment]
Thank you for pointing out this misalignment. Will add a notice about the reference. 

For long term, it is an planned enhancement item. To implement conditional constraint objective, a custom model needed to be trained which may not feasible due to some reasons. One of the planned item is including a additional step to validate augmented result such that it respects to original label (i.e. data augmentation) or leading model to classify augmented result to other label but not original label (i.e. adversarial attack).
