### ISSUE TITLE
Guide for word-level data augmentation

### ISSUE THREAD

**Issue by waterflyer** [makcedward/nlpaug#45]
Hey Edward, 
I'm exploring your algorithms one by one, for word-level augmentation methods, I have tested almost all of them, so I wanted to combine them together to create a pipeline which uses these methods to do augmentation against each row in a pandas dataframe but I got the error 
![image](https://user-images.githubusercontent.com/23243356/65047908-dfe8b580-d928-11e9-8619-1d51e6c8f525.png)

The logic is very simple, the main function is similar as following code
`def word_level_augmentation(dataframe, n_times):
       data_aug = []
       for _, row in dataframe.iterrows():
             text = row['text']
             label = int(row['label'])
             data_aug.append([text, temp_id])
             for _ in range(n_times):
                   data_aug.append([random_word_aug.swap(text), label ])
                   data_aug.append([random_word_aug.delete(text), label ])
                   data_aug.append([spelling_aug.augment(text), label ])

    return data_aug`
Btw, I have used the same function to consume character-level augmentation successfully, so I'm wondering where did I implement incorrectly? Could you help me? 
Thank you so much.

**Comment by makcedward** [comment]
Instead of using those function (e.g. `swap`, `delete`), you may consider to use `augment` function. Just need to pass the `action` when you initialize augmenter. It is because there will have more checking and operation when using `augment` function. 

For example, 
swap_random_word_aug = RandomWordAug(action="swap")
delete_random_word_aug = RandomWordAug(action="delete")

aug_text1 = swap_random_word_aug.augment(text)
aug_text2 = delete_random_word_aug.augment(aug_text1) 

For combing multiple augmenters, you may consider to use `sequential` or `sometimes` augmenter. You may visit here for [examples](https://github.com/makcedward/nlpaug/blob/master/example/flow.ipynb).
